### ISSUE TITLE
Not working in 4.0.7

### ISSUE THREAD

**Issue by voiprodrigo** [reneeb/otrs-DisableOTRSBusinessNotification#1]
Hello,

I'm installing this by manually placing the file in Kernel/Config/Files. But no effect. Using 4.0.7.

Rgds

**Comment by reneeb** [comment]
Did you set the permissions accordingly? Are there any messages in the logs?

**Comment by voiprodrigo** [comment]
No messages in the logs. I think I'm doing it correctly, the sopm says 644:

root@support:/opt/otrs/Kernel/Config/Files# ls -l ZZZZDisableOTRSBusinessNotification.pm 
-rw-r--r-- 1 otrs www-data 481 Apr 27 15:28 ZZZZDisableOTRSBusinessNotificationn.pm

**Comment by voiprodrigo** [comment]
Changed to www-data owner and 660, to match other .pm's on the same dir, but same result.

**Comment by voiprodrigo** [comment]
Ok, I just installed the OPM, given that it's very innocuous, and it works... I have no idea why it doesn't work with the module installed manually, clearly I'm missing something. The weird thing is that I did this on two systems, the notification is removed on both of them, but on one of them I also get a red notification because the package is not verified, but on the other system it doesn't seem to care.

**Comment by voiprodrigo** [comment]
Closing as not an issue after all.
