### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by julenl** [reneeb/otrs-DisableOTRSBusinessNotification#3]
Thank you very much for your plug-in!
However, I am new to OTRS and I still haven't managed to figure out how to apply it properly.
I have copied the `ZZZZDisableOTRSBusinessNotification.pm` file into `/opt/otrs/Kernel/Config/Files` (CentOS 7), but I don't know where to put the `DisableOTRSBusinessNotification.sopm` file. Maybe I am doing it completely wrong...

**Comment by reneeb** [comment]
You should install the OPM: https://opar.perl-services.de/dist/DisableOTRSBusinessNotification
