### ISSUE TITLE
Issues deploying settings in 6.0.8

### ISSUE THREAD

**Issue by KimmoJ** [reneeb/otrs-DisableOTRSBusinessNotification#5]
I'm trying to apply the OTRS 6 version of this on my freshly upgraded 6.0.8, and I'm seeing failures in deploying two changes OTRS wants after installing the plugin.

"There was an error. Please save all settings you are editing and check the logs for more information.
Invalid setting: Ticket::Type::Default"

The system log says:

Mon Jul  9 14:47:50 2018 | error | OTRS-CGI-10 | Need GroupName!
Mon Jul  9 14:47:02 2018 | error | OTRS-CGI-10 | Setting Ticket::Type::Default Effective value is not correct: Entity value is invalid(Unclassified)!
Mon Jul  9 14:46:28 2018 | error | OTRS-CGI-10 | Need Name!

Getting rid of that arrogant and annoying constant whining about the paid version would be very nice, so any chance of figuring out what's wrong? Thanks.

**Comment by KimmoJ** [comment]
My mistake, I found the issue. My tickets lacked a default type setting in OTRS, had to go digging in the admin settings, and found it. So not really an issue with this great addon, a configuration error in my OTRS made it impossible to deploy settings.

**Comment by joelfan** [comment]
Can you please tell me where can I configure this default type?
I cannot find it in the admin settings.

**Comment by KimmoJ** [comment]
If you go to the system configuration section and search for "Default" you should find it. Or specifically, entering Ticket::Type::Default in your search should pinpoint it.
